#include "Referee.hpp"
#include "CAPrinter.hpp"
#include "CSGPrinter.hpp"
#include "CHGPrinter.hpp"
#include "CLGPrinter.hpp"
#include "CSIPrinter.hpp"
#include "CSNPrinter.hpp"
#include "Cmanager.hpp"
#include <iostream>
#include <string>
#include <stdlib.h>
#include <iomanip>
#include <fstream>